# -*- coding: utf-8 -*-
"""Fase 5_Codígo Problema 3 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MWdqt8LYCTqb-kDVS4gB4wyn_ttBwoyW

### Nombre: Karen Gonzalez
### Grupo: 879
### Programa: Ingeniería de Sistemas
### Código Fuente: Autoría propia
"""

# Matriz de inventario
inventario = [
    [101, "Mouse", 10, 15],
    [102, "Teclado", 20, 15],
    [103, "Monitor", 5, 10],
    [104, "USB", 30, 25],
    [105, "Impresora", 2, 8]
]

# Función para calcular la cantidad a pedir
def calcular_pedido(stock_actual, stock_minimo):

    if stock_actual < stock_minimo:
        return stock_minimo - stock_actual
    else:
        return 0


# Título
print("===================================")
print("      LISTA DE PEDIDOS")
print("===================================")

# Recorrer la matriz
for articulo in inventario:

    codigo = articulo[0]
    nombre = articulo[1]
    stock_actual = articulo[2]
    stock_minimo = articulo[3]

    # Llamado de la función
    cantidad_pedir = calcular_pedido(stock_actual, stock_minimo)

    # Mostrar resultados
    print(f"Artículo: {nombre}")
    print(f"Código: {codigo}")
    print(f"Stock actual: {stock_actual}")
    print(f"Stock mínimo: {stock_minimo}")
    print(f"Cantidad a pedir: {cantidad_pedir}")
    print("-----------------------------------")